### PR TITLE
fix "Verison: " in use_dev_version()

### PR DESCRIPTION
**Pull request by tjmahr**

### CODE REVIEW

**Comment by hadley** [comment]
Can you please add a bullet to news too?

**Comment by tjmahr** [comment]
Done!

**Comment by hadley** [comment]
Can you please credit yourself with `(@yourname, #issuenumber)`.

**Comment by tjmahr** [comment]
Okay. I used this pull request number as the issue number because I didn't open an issue. (It was such a quick fix.)

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
