### PR TITLE
GitHub host improvement handling for GHE

### PR DESCRIPTION
**Pull request by cderv**
This is to see what it would mean to support GHE on usethis. a `host` argument has been introduce in some functions, but not all. This follow an issue in #834 that has been solved by providing `GITHUB_API_URL` env var that `gh` depends on. 

usethis can also depends on that by default as it uses `gh` and not offer a `host` argument in each function. It could also take the same approach as for token and check internally `github_api_host()` for this environment variable, default to GH if not set. 

```r
github_api_host() <- function() {
  # NULL means use gh default
  Sys.getenv("GITHUB_API_URL", NULL)
}
```
As `gh` does already this, this could be unnecessary in usethis.

Adding a host argument everywhere it is required seems to be a lot (from what I found already - see the changes)

Some functions (`pr_create_gh`) are using a url not configurable for now and won't work with GHE. It is not the API url but the server url. A `GITHUB_URL` env var maybe ? 🤔 

This is just to put the thoughts somewhere. Hence the draft PR for now.

### CODE REVIEW

**Comment by ijlyttle** [comment]
This is a very interesting topic to me; just a small note to commit (at least to myself) to contribute my thoughts here in the next couple days :)

**Comment by ijlyttle** [comment]
First to apologize provisionally to @cderv, as this post seems like it is hijacking the thread. I am happy to remove this and to post it elsewhere, at the group's suggestion.

I have been thinking about an approach is likely too ambitious to be practical; I can appreciate the discipline of taking modest steps. Perhaps I can present it here, among colleagues, in the hopes that more discussion will follow towards the right practical solution.

There are a few r-lib packages (usethis, remotes, and pak come to mind; there may be others) that rely on or interact with git and github. I think that this idea could be used by other packages, should they wish.

I wonder if there could be a list of "r-lib" github options, like follows:

```r
rlib.github.default <- 
  list(
    service = "github",
    name = "GitHub"
    host_git = "github.com",
    url_api = "https://api.github.com",
    url_web = "https://github.com",
    env_token = c("GITHUB_PAT", "GITHUB_TOKEN")
  )
```

I have "renamed" some of the elements to try to identify more clearly what each element does; I note that the definition of `host` can vary from function to function (e.g. `remotes::install_github()`, `usethis::create_from_github()`, `usethis::browse_github_pat()`).

Perhaps this option could be a hardwired default, so that if someone wanted to use an instance of GitHub Enterprise (GHE), they could add something like this to their `.Rprofile`:

```r
options(
  rlib.github = list(
    list(
      service = "ghe_acme",
      name = "Acme GitHub Enterprise"
      host_git = "github.acme.com",
      url_api = "https://github.acme.com/api/v3",
      url_web = "https://github.acme.com",
      env_token = "GITHUB_PAT_ACME"
    )
  )
)
```

The overall idea is that public-facing functions that touch github (public or GHE) could add a `service` argument that could be used to determine the rest of the information. For organizations that use GHE, it would be their responsibility to publicize internally the "thing" that folks would put in their `.Rprofile`.

I think of functions in four categories:

- creating at github: `usethis::use_github()`
- creating from github: `usethis::create_from_github()`, `remotes::install_github()`
- interacting with github: `usethis::pr_*()`
- utilities: `usethis::github_token()`, `usethis::browse_github_token()`, `usethis::git_sitrep()`

For creating at github, I might suggest a default of `service = NULL`. If there is only one service available (github), it would use it. If there are multiple services available, and none is specified, the user could be told to supply an explicit choice.

For creating from github, I perhaps `service = "github"` could work as a default. I could also see wanting to be explicit.

For interacting with github, the `pr_*` functions, I don't think a `service` argument would be appropriate. Instead, I think these functions could look at the git-remote address for `origin` or `upstream`, e.g. `git@github.com:r-lib/usethis.git`, pull out the `host_git`, then use the matching service.

For the utility functions, I think `service = "github"` would work OK. For `usethis::git_sitrep()`, perhaps it could report on the status of all the registered services, and let the user know which of the services is being used for a local repo.

To wrap up, I recognize that this idea may not be a practical way forward, and I am happy to move the discussion to wherever it should go...

**Comment by jennybc** [comment]
Thanks to you both for pushing this along.

@ijlyttle Your proposal sounds quite interesting and feels compatible with where we are w.r.t. the `auth_token` and git credentials. I think you should open a new issue and copy what you above there, as a better place to store it.

The next big thing I will do here, after pushing a few more gargle-related things out, will be to (hopefully) move usethis onto gert + credentials, to eliminate a lot of our git credentials pain. I will be touching all the git bits here and that could be a time to do something like what you propose.

I'll also raise this with others re: whether we could have a multi-package approach to some of this.

**Comment by ijlyttle** [comment]
@jennybc Will do, thanks!

**Comment by jennybc** [comment]
The landscape has changed here and ultimately I think this problem will be solved in other ways. For now I'm leaving this open as an interesting resource for when I get to solving the GHE problem.

**Comment by cderv** [comment]
Glad it is still useful 😄 

I have seen the different evolution from afar as I did not have time yet to contribute in discussion. I will have more soon if you need 👀 on anything.

**Pull request closed without merging**
