### PR TITLE
Reorder the messages in edit_r_profile, edit_renviron and rprofile-helper functions

### PR DESCRIPTION
**Pull request by llrs**
This PR changes the order of the messages that the user sees when editing the Rprofile and the Renviron file as proposed on #732.

### CODE REVIEW

**Comment by hadley** [comment]
Can you please change the title of this issue to be informative?

**Comment by llrs** [comment]
Done

**Comment by jennybc** [comment]
I no longer remember why I was so anxious about this. I'll merge and try to play with a bit to make sure I'm not missing something obvious.

**Comment by llrs** [comment]
Great! (I also didn't understand what were the problems with this reordering, but let's see if there is any trouble down the line)

**Pull request merged**
