### PR TITLE
Export use_git_ignore()

### LINKED ISSUE #3: use_git_ignore()
and perhaps `use_ignore()` which adds to both `.Rbuildignore` and `.gitignore`.

### PR DESCRIPTION
**Pull request by krlmlr**
Fixes #3.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Sorry for the delay. The export is fine, but there are some unrelated changes here as well. FYI.

**Comment by krlmlr** [comment]
Yes, forgot to mention. I could file them to a separate PR, but I thought it's not worth the effort.

**Comment by gaborcsardi** [comment]
No big deal, just mentioning it just in case.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
