### PR TITLE
Use cli in messages

### LINKED ISSUE #956: Migrate ui_*() functionality to use cli
See notes here: https://github.com/r-lib/cli/issues/68

and the transition guide: https://cli.r-lib.org/dev/articles/usethis-ui.html

### PR DESCRIPTION
**Pull request by olivroy**
fix #956 

This is a rough draft. I would understand you'd rather take this on yourself, but in case it could be of any use, I thought I'd share!

Edit: CI won't cooperate. but anyway. I will try this branch of usethis installed locally and will update if something goes wrong.

Edit2 : feel free to take anything that you like from this!

## List of problems

* Can't figure out how to [have red bullets](https://cli.r-lib.org/articles/usethis-ui.html#how-to).

## Nice to have?

ui_code that is meant to be run and other that is not meant?

## Results

Impact of changes in be8a0f0

image

## not covered by tests

* `git_sitrep()`: may be a problem as it uses `ui_todo with multiple lines input extensively, and is not really tested)
* `pr_push()`

### CODE REVIEW

**Comment by jennybc** [comment]
Thanks for taking this on! In terms of me planning when to turn my attention to this and review it, do you consider it semi-done now? As in, you're at a stopping place and the PR is in a good state for review and discussion?

**Comment by olivroy** [comment]
I consider it to be semi-done! 

The biggest issue is how glue / crayon handles Linebreaks and whitespace differs.

I'd say my biggest concern is that I modified the `ui_*()` functions thinking only of usethis UI, and ignoring revdeps, which is why my PR may not be the correct way forward.
I also haven't edited any documentation, but will do this after review!

I will continue to play with it, and my further contributions would just be to patch how usethis messages look / feel, as I use usethis from this branch more!

For the reiview, I would look at the test changes, the changes of the `ui_*()` functions. (mostly whitespace / linebreaks changes or issues)

I could not figure out how to make the bullet for `ui_todo()` red, nor the info yellow for `ui_info()`, (not mentioned in the [cli guide](https://cli.r-lib.org/articles/usethis-ui.html) either.

**Comment by olivroy** [comment]
@jennybc Feel free to take a look! I encountered few issues since my last commit

**Comment by olivroy** [comment]
@jennybc, it broke options(usethis.quiet), would you have any advice on making it work for cli? 

I couldn't quite figure out how it works currwntly.

**Comment by jennybc** [comment]
I should let you know I now have my own branch where I'm doing the cli conversion with a pretty different approach. So you might want to pause this effort 😅

**Comment by olivroy** [comment]
Excited to see it! Let me know if you want me to test it!

**Comment by jennybc** [comment]
#1956 has finally landed! I'd welcome comments from you, but you should not feel obligated if you don't have the time or interest. But given all the work you did here (I know how much it is!), I thought you might want to take a look. I will merge #1956 fairly soon, because I think it's clearly a huge step forward and the real proof will be in having some folks use the dev version and kick the tires.

**Pull request closed without merging**
