### PR TITLE
fuhgeddaboudit

### PR DESCRIPTION
**Pull request by jtr13**
Testing a PR with "Allow edits from maintainers." UNCHECKED

### CODE REVIEW

**Comment by jennybc** [comment]
Yeah I can definitely override the user's setting re: whether maintainer can modify the PR.

**Comment by jtr13** [comment]
Wow, wasn't expecting that!

**Comment by jtr13** [comment]
If you want me to test it the other way around, submit a PR on https://github.com/jtr13/usethis_demos (maybe you have github superpowers)

**Comment by jennybc** [comment]
Thanks for your help!

**Comment by jtr13** [comment]
Anytime. Love this stuff & learning a lot.

**Pull request closed without merging**
