### PR TITLE
Remove some git /github related defunct functions

### PR DESCRIPTION
**Pull request by olivroy**
As they clutter the autocompletion?

I did gh code search and the functions don't seem widely used as people have made the switch over the last 3.5 years. I opened a few PRs and issues as FYI to avoid ugly messages in advance.

I also added a few redirection rules in pkgdown config to be on the safe side!

https://github.com/search?q=saved%3A%22usethis+deprecate%22+&type=code&saved_searches=%5B%7B%22name%22%3A%22usethis+deprecate%22%2C%22query%22%3A%22browse_github_pat++NOT+is%3Aarchived+NOT+is%3Afork%22%7D%5D&expanded_query=browse_github_pat++NOT+is%3Aarchived+NOT+is%3Afork+

### CODE REVIEW

**Comment by jennybc** [comment]
>  I opened a few PRs and issues as FYI to avoid ugly messages in advance.

Can you mention this PR in those PRs and issues, so they get linked here and I can see exactly what you're talking about?

**Comment by olivroy** [comment]
https://github.com/annakrystalli/rrresearchACCE20/issues/14
https://github.com/annakrystalli/talks/issues/9
https://github.com/jimbrig/property_allocation_demo/issues/4
https://github.com/Edouard-Legoupil/kobocruncher/issues/11
https://github.com/Edouard-Legoupil/kobocruncher/issues/11
https://github.com/KWB-R/kwb.pkgbuild/issues/92
https://github.com/tlverse/tlverse-handbook/issues/35
https://github.com/tlverse/tlverse/issues/4
https://github.com/ropensci/circle/pull/42

https://github.com/SticsRPacks/documentation/pull/2
https://github.com/matt-dray/rostrum-blog-2/pull/41
https://github.com/MazamaScience/AirSensorDataViewer/pull/60
https://github.com/rstudio/shinycoreci/pull/266

Mostly mentioned in older docs

**Comment by jennybc** [comment]
This is not in scope for the next release, as it looks pretty fiddly, for a modest payoff.

In order to sort this out, it would be helpful to make it clear which of the PRs are to packages on CRAN/Bioconductor (which we cannot break, at least not without sufficient warning) vs. other stuff (blog posts, talks, etc., where the issue/PR is just courtesy).

**Comment by olivroy** [comment]
The PRs are all curtesy. No breakage will happen. As you can see, the PRs and issues have mostly been ignored (namely becsuse they were on old unmaintained projects) The only reason why I added redirects in _pkgdown.yml was as curtesy, but they are not required.

**Comment by jennybc** [comment]
Thanks!

**Comment by jennybc** [comment]
> The PRs are all courtesy. No breakage will happen. 

It turns out `github_token()` is used by a package on CRAN:

https://github.com/ropensci/circle/blob/f8a4fbf6f792c3f462df1749b90cca9c31214e3a/R/use-circle-deploy.R#L39

**Comment by olivroy** [comment]
I didn't catch this occurrence in my search.. but this function is broken (and has been for a while now)

**Comment by jennybc** [comment]
I don't think this matters much in practice, because I suspect that the use of this package (circle) is minimal / non-existent, given how much folks have pivoted from Circle CI to GitHub Actions. In any case, usethis made it onto CRAN even with this mild breakage, since `github_token()` has been hard deprecated since December 2020. If this was actually bothering folks, it would have been updated by now.

**Pull request merged**
