### PR TITLE
Scripts to use clang-format locally and on travis

### PR DESCRIPTION
**Pull request by jimhester**
Potentially we could have an RStudio addin to run clang-format locally as well, there are already extensions for vim and emacs and Sublime that can be run automatically.

### CODE REVIEW

**Comment by jimhester** [comment]
Unfortunately the travis image on precise includes a very old version of clang-format (3.4) which does not have all the options we settled on for readr (https://github.com/tidyverse/readr/pull/651/files#diff-88d5907f11b8b6ca0b213de568bf4582R2).

We could update the instructions to include a newer clang-format, 3.9 is available from whitelisted sources, and modify the script to call clang-format-3.9 if `clang-format --version` is 3.4, but it would require a few more lines in .travis.yml.

**Comment by hadley** [comment]
Can this be tweaked now that travis is using a newer base image?

**Comment by jennybc** [comment]
@jimhester The plan is to submit this around the end of the CRAN holiday, to make sure it's solid for rstudio::conf workshops. Do you want to get this into the next release or let it be for now?

**Comment by jennybc** [comment]
A usethis release is on the horizon. Periodic check on whether it's a good time to advance this.

**Comment by jennybc** [comment]
This is my traditional check to see if I should be moving on this @jimhester, with another release on the horizon.

**Comment by jimhester** [comment]
I think it can continue to wait, I need to revisit it and see if I can simplify things somehow...

**Comment by jennybc** [comment]
This is my traditional check to see if I should be moving on this @jimhester, with another release on the horizon.

Or should we close it?

**Comment by hadley** [comment]
I think we should mercy kill this

**Comment by franzbischoff** [comment]
This is working for me, is it difficult to implement?

reads the config from .clang-format file at the project root
```R
processx::run("clang-format", c("-i", "--style=file", "myfile.cpp"))
```

**Pull request closed without merging**
