### PR TITLE
Use proj_path_prep() on path from rstudioapi

### LINKED ISSUE #479: Have `usethis::proj_path_prep()` use `fs::path_abs(fs::path_expand())` instead of `fs::path_real()`
usethis currently uses `fs::path_real()` to determine the project path, however this poses problems when the path is a mapped network drive on Windows, because the root no longer can be calculated relative to the input path.

I map my R projects folder to my windows VM, so I run into this situation often.

I propose to instead use `fs::path_abs(fs::path_expand())`.

``` r
usethis::proj_set("Z:/projects/remotes")
#>  Setting active project to '//vmware-host/Shared Folders/projects/remotes'
usethis::use_test()
#> Error: Open file must be in the 'R/' directory of the active package.
#> * Actual path: 'Z:/projects/remotes/R/submodule.R'
fs::path_real("Z:/projects/remotes/R/submodule.R")
#> //vmware-host/Shared Folders/projects/remotes/R/submodule.R
fs::path_abs(fs::path_expand("Z:/projects/R/submodule.R"))
#> Z:/projects/R/submodule.R

fs::path_real("~/Links")
#> C:/Users/IEUser/Links
fs::path_abs(fs::path_expand("~/Links"))
#> C:/Users/IEUser/Links
```

Created on 2018-10-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

### PR DESCRIPTION
**Pull request by jennybc**
Closes #479 Have `usethis::proj_path_prep()` use `fs::path_abs(fs::path_expand())` instead of `fs::path_real()`

This causes 4 tests to fail. One was an easy and positive fix. One could be fixed (removed?), as it is literally testing for path realization. That is the first failure you see below.

The remaining 2 failures suggest a concrete reason why I used `path_real()` in the first place: `rprojroot::find_root()` returns a normalized path, in the sense of `normalizePath()`. That would not be particularly easy to fix / workaround.

This points out the difficulty of adopting a fs mindset when handing paths to/from other packages that use the base path handling toolkit. I have experienced similar pain with paths from RStudio via rstudioapi.

So if we want to do this, we will need to somehow put more wrapping around  `rprojroot::find_root()`. *Update: or, alternatively, more wrapping around any paths created by rstudioapi.*

### CODE REVIEW

**Comment by jennybc** [comment]
``` r
> test(filter = "proj")
Loading usethis
✔ Setting active project to '/Users/jenny/rrr/usethis'
Testing usethis
✔ | OK F W S | Context
✖ | 25 3     | projects [0.5 s]
───────────────────────────────────────────────────────────────────────────────────────────────────────────
test-proj.R:85: failure: proj_set() enforces proj path preparation policy
path_rel(proj_get(), a) not equal to "b/d".
1/1 mismatches
x[1]: "b2/d"
y[1]: "b/d"

test-proj.R:136: failure: with_project() runs code in temp proj, restores original proj
res[["active_usethis_proj"]] not identical to as.character(new_proj).
1/1 mismatches
x[1]: "/private/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpI8hOSz/aaa922a2cabc31b"
y[1]: "/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpI8hOSz/aaa922a2cabc31b"

test-proj.R:154: failure: local_project() activates proj til scope ends
res[["active_usethis_proj"]] not identical to as.character(new_proj).
1/1 mismatches
x[1]: "/private/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpI8hOSz/aaa922a40963886"
y[1]: "/var/folders/yx/3p5dt4jj1019st0x90vhm9rr0000gn/T/RtmpI8hOSz/aaa922a40963886"
───────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 0.6 s

OK:       25
Failed:   3
Warnings: 0
Skipped:  0
```

**Comment by krlmlr** [comment]
I don't mind updating _rprojroot_ to use _fs_, if that helps.

**Comment by hadley** [comment]
(@jennybc I updated this PR against master so make sure to `pr_pull()` it if you start working on it again. I did this to test my PR tooling, and indeed it found several bugs)

**Comment by jennybc** [comment]
@jimhester Will you try this PR and see if it fixes your workflow on a Windows VM with a mapped network drive?

This iteration processes a path from rstudioapi as if it was an external user-provided path.

**Comment by jennybc** [comment]
@jimhester We will release usethis soon. If you're still interested in this (I am!), will you try this PR and see if it fixes your workflow on a Windows VM with a mapped network drive?

This version processes a path from rstudioapi as if it was an external user-provided path.

**Pull request merged**
