### PR TITLE
Use badges from shield.io in `use_badges_functions()`

### LINKED ISSUE #925: Feature: Use badges from shield.io in `use_badges_*` functions
- Contain the logo of the CI system which makes badges easier to differentiate 
- Contain the OS system which was used for building (only for Circle and Appveyor since Travis provides multiple ones)
- point by default to the master branch

# Preview

[Travis build status](https://travis-ci.org/r-lib/usethis)
[AppVeyor build status](https://ci.appveyor.com/project/r-lib/usethis)
[CircleCI build status](https://circleci.com/gh/r-lib/usethis)

### PR DESCRIPTION
**Pull request by pat-s**
fixes #925

### CODE REVIEW

**Comment by hadley** [comment]
@gaborcsardi @jimhester do you see any problems with switching to shield.io?

**Comment by gaborcsardi** [comment]
No problems in principle, but fwiw from my location shield.io is quite slow, and afair this has always been the case.

```
❯ time curl 'https://travis-ci.org/r-lib/ps.svg?branch=master' -s -o /dev/null
curl 'https://travis-ci.org/r-lib/ps.svg?branch=master' -s -o /dev/null  0.02s user 0.01s system 4% cpu 0.548 total

❯ time curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o /dev/null
curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o   0.02s user 0.01s system 0% cpu 5.602 total

❯ time curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o /dev/null
curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o   0.01s user 0.01s system 1% cpu 1.777 total

❯ time curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o /dev/null
curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o   0.02s user 0.01s system 2% cpu 0.847 total

❯ time curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o /dev/null
curl 'https://img.shields.io/travis/r-lib/usethis/master?logo=travis' -s -o   0.02s user 0.01s system 2% cpu 0.894 total
```

**Comment by hadley** [comment]
Hmmm, I also wonder generally about using a separate provider for this. Seems safer to stick with the badge that the service provides.

**Comment by gaborcsardi** [comment]
Yeah. Although, on GitHub the images are cached by GitHub, anyway, so speed does not matter that much.

**Comment by jimhester** [comment]
We are also increasing moving away from using multiple CI providers, so having the logo is not really that important. IMHO I would just stick with what we have currently.

**Pull request closed without merging**
