### PR TITLE
Add use_logo function to add a logo to a package

### LINKED ISSUE #358: `use_logo()` to add a hex logo to the package, give you text for the README
Ideally this would take an input, resize it to some standard size (120x140?), put it in `man/figures/logo.png` and generate the text to add to `README.{R,}md` e.g. ``

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #358

### CODE REVIEW

**Comment by jimhester** [comment]
Oh, likely we just need `libmagick++-dev` on Travis, I will add it tomorrow

**Comment by jimhester** [comment]
And the difference is magick failed to install because of a missing system dependency

**Comment by jennybc** [comment]
Are you planning to do something that would affect all R travis builds or something specific to this package, along the lines of what magick itself does?

https://github.com/ropensci/magick/blob/master/.travis.yml

**Comment by jimhester** [comment]
Ok should be fixed now, sorry I wasn't able to get to this yesterday!

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
