### PR TITLE
Remember to update README.Rmd

### LINKED ISSUE #923: Add to release checklist: check that README.md and index.md are up-to-date

### PR DESCRIPTION
**Pull request by hadley**
Similarly to `rename_files()` I'm most worried about the name of this function (and if it is really a usethis function)

Fixes #923

### CODE REVIEW

**Comment by jimhester** [comment]
We already have `devtools::build_readme()`...

**Comment by hadley** [comment]
TIL 🤣 

I think that's almost uniformly better; it just needs to pass `html_preview = FALSE`; I'll do a devtools PR.

**Comment by jimhester** [comment]
Great thanks!

**Comment by hadley** [comment]
I really should've just made a new PR 🙄

**Pull request merged**
