### PR TITLE
add `scope` arg to pat_sitrep()

### LINKED ISSUE #1732: `scope` argument for `pat_sitrep()`?
In `git_sitrep()`, `pat_sitrep()` is called for both `"user"` and `"project"` scopes. Regardless of scope, it consults the `"de_facto"` git email:

https://github.com/r-lib/usethis/blob/8104204fcd78eeb1d7588c1fd5882f707ff1e54a/R/github_token.R#L182

If reporting for the `"user"` scope, I think it should consult the `"global"` email address.

I think this could be addressed by adding a `scope` argument to `pat_sitrep()`; happy to offer a PR.

### PR DESCRIPTION
**Pull request by ijlyttle**
fix #1732

This allows `gh_token_help()` to check git's `"global"` email when reporting at the `"user"` level.

### CODE REVIEW

**Comment by ijlyttle** [comment]
quick note - I should have put a "draft" on this - I'm still sorting out some merge issues, I'll send a signal when I've got them sorted.

**Comment by ijlyttle** [comment]
@jennybc, this is ready now.

Sorry for the messy route; thank goodness for squash-and-merge 😅

I run this from the usethis directory, where I have a *local* git user.email: 

```r
withr::with_envvar(
  list(GITHUB_API_URL = "https://github.<work>.com/api/v3"), 
  git_sitrep(scope = "user")
)
```

I get the response I expect:

```
── Git global (user) 
• Name: 'Ian Lyttle'
• Email: 'ian.lyttle@<work>.com'
• Global (user-level) gitignore file: '~/.gitignore'
• Vaccinated: TRUE
• Default Git protocol: 'https'
• Default initial branch name: 'main'

── GitHub user 
• Default GitHub host: 'https://github.<work>.com'
• Personal access token for 'https://github.<work>.com': '<discovered>'
• GitHub user: '<work-id>'
• Token scopes: 'gist, repo, user, workflow'
• Email(s): 'ian.lyttle@<work>.com (primary)'
```

**Comment by ijlyttle** [comment]
pointing this to fix #1722

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
