### PR TITLE
export use_github_action function

### PR DESCRIPTION
**Pull request by smwindecker**
Discussed with @jimhester this morning at ozunconf that this functionality to call actions from marketplace url's should be exported

### CODE REVIEW

**Comment by jimhester** [comment]
LGTM, thanks @smwindecker!

**Comment by jennybc** [comment]
@smwindecker I think you need to run `devtools::document()` to that the new export causes the requisite change in `NAMESPACE`.

I'll eventually do this myself and merge, but if you do it first, even better.

**Comment by jimhester** [comment]
@jennybc the namespace already has the change in this PR unless I am missing something https://github.com/r-lib/usethis/pull/958/files#diff-7347fe5a0f184f79ef064e92e3beb297R106

**Comment by jennybc** [comment]
> @jennybc the namespace already has the change in this PR unless I am missing something

Oh, that's odd, isn't it 🤔? I mean ... how did that happen? I was just looking at this PR in isolation.

**Comment by jennybc** [comment]
Oh, sorry. Nevermind all.

**Comment by smwindecker** [comment]
Thanks @jennybc! Yes not sure why it looked like a check had failed. I felt pretty confident leaving it though, as I knew the documentation was updated.

**Comment by jennybc** [comment]
The travis failure is some other, unrelated thing. This looks like an intermittent failure, plus there are at least 2 other travis gremlins lurking this week. No worries.

**Pull request merged**
