### PR TITLE
Never lower an R version requirement in `use_data()`

### PR DESCRIPTION
**Pull request by jennybc**
Closes #2077

### CODE REVIEW

**Comment by jennybc** [comment]
@olivroy Do you remember which standalone file caused the minimum R version to be downgraded for you?

Another option I was considering is a specialized `use_package()` helper for R itself, i.e. splitting that out so that `use_package()` can just focus on normal packages. I'll explore that solution as well.

**Comment by jennybc** [comment]
`use_test()` only calls `use_testthat_impl()` if the package doesn't use testthat yet. So that doesn't seem like it would really contribute to this problem. I'm not saying you didn't experience it with some specific set of moves, but in the main use case, I don't see the connection there.

**Comment by olivroy** [comment]
Ok! simple repro case..

If I have in DESCRIPTION, 


```
Imports:
  rlang (>= 1.1.4)
```

With dev usethis,
I call `usethis::use_standalone("r-lib/rlang", "types-check")`, which [requires rlang 1.1.0](https://github.com/r-lib/rlang/blob/38eb82d2a952fd219ded73a5a2aec894d95505aa/R/standalone-types-check.R#L7).

It will decrease the dependency of rlang silently.

**Comment by jennybc** [comment]
I'm just going to worry about not downgrading the required version of R. I think `use_standalone()` is enough of an expert-use only function that said expert can also decide not to stage that particular change.

**Pull request merged**
