### PR TITLE
Set a flag to always tidy the description

### LINKED ISSUE #1379: Should use_tidy_description() set a config flag?
e.g. `Config/usethis/auto_tidy: TRUE` so that afterwards, any operation that touches the description would auto-tidy it?

### PR DESCRIPTION
**Pull request by hadley**
Fixes #1379

Having implemented this, I'm not sure that usethis is the right place. @gaborcsardi what do you think moving the `$write()` logic into desc itself? That would guarantee every desc operation tidies, not just those that go through `proj_desc()`.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Yes, that would make sense.

**Comment by jennybc** [comment]
I like the idea to put this in desc instead.

**Comment by hadley** [comment]
@gaborcsardi maybe `Config/desc/tidy: true` ?

**Comment by gaborcsardi** [comment]
That is good, yes.

**Comment by jennybc** [comment]
So, as far as usethis is concerned, this is something we should add to the default `DESCRIPTION` we create, yeah? Or is it something we recommend people configure as a personal preference?

**Comment by hadley** [comment]
We'd add it by default, I think.

**Comment by hadley** [comment]
I'll file a follow up issue once I've added the functionality in desc

**Pull request closed without merging**
