### PR TITLE
Attempt to bubble up failure message from rprojroot::find_root

### LINKED ISSUE #1795: "not in a project" error could be more helpful
https://github.com/r-lib/usethis/blob/654a96576bca12f33aa81cab98fb19b4d0db1f1b/R/proj.R#L87

I tried running `use_package_doc()` in a directory and got this error. As near as I can tell it's being run in the project directory, so the error is a bit frustrating because it's not actionable.

Ideally, we'd spell out exactly what "inside a project or package" means, but I understand that might require exposing implementation details.

In that case, maybe it would be helpful to just refer to `rprojroot::find_root()` instead?

https://github.com/r-lib/usethis/blob/654a96576bca12f33aa81cab98fb19b4d0db1f1b/R/proj.R#L188

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #1795 

Alternatively, we might just re-use this snippet:

https://github.com/r-lib/usethis/blob/654a96576bca12f33aa81cab98fb19b4d0db1f1b/R/proj.R#L221-L222

### CODE REVIEW

**Comment by jennybc** [comment]
These functions are a real hot spot for introducing bugs, so I'm not eager to change them for something that seems to be a very rare problem.

So, yeah, I'd prefer to handle by suggesting folks read more in the help for `proj_get()` or by executing `rprojroot::find_root()` themselves.

**Comment by MichaelChirico** [comment]
Thanks! Minimal version of that done now.

Another suggestion would be a small refactor to move the error down into `proj_get()` to avoid duplication, or, to keep the internal API as-is, move the error into a wrapper function and call it twice. LMK what you prefer.

**Comment by jennybc** [comment]
Thanks!

**Comment by MichaelChirico** [comment]
thanks for the guidance and tidying up, looks great!

**Pull request merged**
