### PR TITLE
prefer no spaces between arguments in chunk options

### PR DESCRIPTION
**Pull request by kevinushey**
A style tweak for the default vignette.

### CODE REVIEW

**Comment by jennybc** [comment]
Problem is, I really dislike that style 😬

Can we discuss context more? Presumably the current template isn't actively harmful, but you must have some reason for preferringnospaces.

**Comment by kevinushey** [comment]
This is mainly because it's the "default" style used in the knitr documentation, e.g.

https://yihui.org/knitr/options/
https://bookdown.org/yihui/rmarkdown/r-code.html

I believe the motivation for this style is mainly to avoid overly-long chunk headers -- saving 2 characters on option does add up.

**Comment by jennybc** [comment]
My inclination is to pass on this one, as I would then need to edit this in new vignettes each time I create one!

I see that @malcolmbarrett seems to agree with me (?). @Hadley do you have an opinion?

**Comment by hadley** [comment]
I really dislike the no-space formatting.

**Comment by malcolmbarrett** [comment]
Yes, TBH I'm always fighting the IDE's autocomplete on this one

**Comment by kevinushey** [comment]
I mean, I prefer spaces as well, but the canonical form for chunk options is no spaces around `=`. This is the form we've chosen to adopt and use in other parts of the IDE as well, e.g. in our existing templates:

https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/templates/document.Rmd

I think it's more important to be consistent with existing convention, especially if that convention is already well-established in existing documentation and tools.

**Comment by jennybc** [comment]
I find that I still feel the same way: I really dislike the no space style.

Maybe the new ability (in knitr 1.35) to specify chunk options in special comments inside the chunk heralds the dawn of a new era, where it's cool to make chunk options more readable 🤓

**Pull request closed without merging**
