### PR TITLE
Add use_stopwords()

### PR DESCRIPTION
**Pull request by kbenoit**
Add `use_stopwords()`, so that this function can be relocated from the [**stopwords** package](https://github.com/quanteda/stopwords).

We added `use_stopwords()` in v2.0, but this introduced too many downstream dependencies via importing **usethis**. It's a very popular package and it would be great to keep the `use_stopwords()`, but it is more logical and efficient to locate this function in the **stopwords** package.

### CODE REVIEW

**Comment by hadley** [comment]
I think this is a bit too specific for usethis. Can we instead help you keep it in stopwords, but with fewer dependencies? (i.e. by moving it to suggests).

**Comment by jennybc** [comment]
For more context, we are also now questioning `use_tibble()` and `use_data_table()`, because once you start adding these sort of helpers, there is no end of it.

**Comment by kbenoit** [comment]
No problem. I'd added it this way https://github.com/quanteda/stopwords/blob/master/R/use_stopwords.R which would not work with usethis in Suggests, but I'm all ears to alternatives. Especially if you are going to issue recommendations for `use_tibble()` and `use_data_table()`, this would be a very useful set of guidelines to wean the package from these and future helpers of this sort.

**Comment by hadley** [comment]
The technique you use there is potential very fragile because the copying happens at package build time, not load time. That means there’s the potential for a mismatch because the installed version of use this and the version of use this that the embedded functions expect.

**Comment by kbenoit** [comment]
@Hadley good point, but what alternative to that sort of code smuggling exists when the source package has banned exports?

**Pull request closed without merging**
