### PR TITLE
Add use_rcpp_armadillo() and use_rcpp_eigen(). (closes #421).

### LINKED ISSUE #421: Feature request: use_rcpp_armadillo() and use_rcpp_eigen()
RStudio provides package templates for packages that use `Rcpp` and `RcppArmadillo`, but if you decide to use `RcppArmadillo` mid-project it can be a bit tricky to remember what goes where. I use `RcppArmadillo` infrequently and can never remember the setup that needs to happen. Having helpers

- `use_rcpp_armadillo`
- `use_rcpp_eigen`

would be incredibly convenient.

### PR DESCRIPTION
**Pull request by coatless**
This is the second coming of PR #601 based on feedback from @jennybc. She requested the unit test design pattern found in PR #645 for testing a package without needing to add it to the Suggests field. This is important as `RcppArmadillo` has a hard dependency for `R >= 3.2.*` while the state of `usethis` allows for `R 3.1.*`.

### CODE REVIEW

**Comment by jennybc** [comment]
Thanks! I made a few small changes, so please speak up if you take issue with them.

**Comment by coatless** [comment]
@jennybc thanks! :+1: on all changes. I take it that for the stylization this was just a call to `styler`?

**Comment by jennybc** [comment]
> I take it that for the stylization this was just a call to styler?

Yep.

**Comment by jennybc** [comment]
Well, I think I removed the full stop in the roxygen title by hand.

https://style.tidyverse.org/documentation.html#title-and-description

**Pull request merged**
