### PR TITLE
Fix issue #1198 ("use_gpl3_license() modifies GPL-3 license text")

### PR DESCRIPTION
**Pull request by fweber144**
This PR is intended to fix [issue #1198](https://github.com/r-lib/usethis/issues/1198) ("use_gpl3_license() modifies GPL-3 license text"). However, I just demonstrated my suggestion for `use_gpl3_license()`. You will probably have to adopt it for the other GPL-like licenses, too.

### CODE REVIEW

**Comment by fweber144** [comment]
I forgot to update the documentation; I will solve that asap.

**Comment by fweber144** [comment]
Documentation is fixed. I also updated the NEWS file and updated the corresponding testthat test. I'm sorry for any inconvenience caused by creating a premature PR. I hope this PR is OK now. But keep in mind that this PR still only applies to `use_gpl3_license()` and probably needs to be adopted for the other GPL-like licenses.

**Comment by jennybc** [comment]
@Hadley Do you have any objection to this? It means our template does less. It becomes a verbatim file.

In two places, we'd leave placeholders as placeholders, instead of populating them via whisker:

https://github.com/r-lib/usethis/blame/00e060017b5e18c6ba5e122d153173419a7f35bb/inst/templates/license-GPL-3.md#L556

https://github.com/r-lib/usethis/blame/00e060017b5e18c6ba5e122d153173419a7f35bb/inst/templates/license-GPL-3.md#L576

**Comment by hadley** [comment]
I think this is correct, although I'd prefer to maintain the existing markdown formatting, just removing the existing whisker templates.

**Comment by hadley** [comment]
Thanks for the PR and for brining this problem to our attention! I've wrapped the fix up into a more comprehensive set of changes at #1208

**Pull request closed without merging**
