### PR TITLE
Address #694: Advice for paths and RStudio Cloud

### PR DESCRIPTION
**Pull request by ijlyttle**
This is a first attempt at providing guidance for how to deal with paths and destination-directories for RStudio Cloud. 

I don't know if this is best addressed in the function-documentation, as done here, or if a bullet point in the setup-article might also (or instead) be merited.

cc @cwickham, to make sure I've got it "right"

### CODE REVIEW

**Comment by cwickham** [comment]
This is what I do, but I'm not sure how I feel about this advice.  I feel like it should convey something more like "If you are using RStudio Cloud you might not want to use `use_course()`, but if you must, we recommend `"/cloud/project"` as a home directory."

Or perhaps, not have this in the documentation, but somewhere else as "problems encountered in teaching usethis".

**Comment by ijlyttle** [comment]
@cwickham Thanks - I'll have another go at it.

I imagine this will keep until after the CRAN release, esp. to decide where the documentation should "live".

**Comment by jennybc** [comment]
I suspect there should be an article about usethis functions that are useful when running a course or workshop. And there could be a section on RStudio Cloud.

**Comment by ijlyttle** [comment]
Sounds good! Will head in that direction.

**Comment by jennybc** [comment]
I'm going to close this, with the expectation that this new content (and probably some of the existing) can move into this future article.

**Pull request closed without merging**
